### ISSUE TITLE
Image storage cloud service

### ISSUE THREAD

**Issue by apurv2** [apurv2/StudentAssistWeb#3]
http://cloudinary.com/
This cloud storage service has a free tier. Needs to be Implemented ( R&D) work.

**Comment by JBaba** [comment]
@apurv2  what's URL for index page ?

**Comment by JBaba** [comment]
@apurv2  Implemented test for one Image to show in details section.

**Comment by apurv2** [comment]
can you provide a screen shot or preview?
also, make the images look like thumbnails so that when clicked they open wide like you described with black overlay on the background.
